### ISSUE TITLE
TASK: Connecting Front-end to Back-end

### ISSUE THREAD

**Issue by christine-morgado** [DegreeMap/DegreeMap#10]
## Description

Wire front-end APIs to back-end APIs. 

### Subtasks

- [ ] First, have the ability to create, login and logout of profiles.
- [ ] Next, have the ability to view your custom course catalog and first degree map upon logging in.
- [ ] Do this by, making so when you make an account, make a userCC and populate it with 3 default courses. Also make a userDM. 
- [ ] After that, on the DM page, pull from userDMs. Likewise for the CC page.

### Acceptance Criteria

- [ ] Data can be pulled from the backend to the frontend.
- [ ] Data can be manipulated (creating DegreeMaps).

### *In-Review* Tasks

- [ ] **EVERYONE** is able to manipulate data.
