### ISSUE TITLE
TASK: Connect Terms to Blocks & Courses

### ISSUE THREAD

**Issue by christine-morgado** [DegreeMap/DegreeMap#11]
## Description

Need to connect terms to courses and blocks. Additionally, have manual testing for all features (for us to see how data is accurately represented in the code).

### Subtasks

- [x] Finish Blocks
- [x] Finish CourseTerms
- [x] Finish manual tests

### Acceptance Criteria

- [x] Create Block JPA entity.
- [x] Create tests for Block.
- [x] Create CourseTerm JPA entity.
- [x] Create tests for CourseTerms.
- [x] Finish manual testing for Course Feature.
- [x] Finish manual testing for DegreeMap with Courses & Blocks in each term.

### *In-Review* Tasks

- [x] Have every backdev review the manual tests.
- [x] Make sure every backend dev has a complete understanding of the JPA structure.
