### ISSUE TITLE
EPIC: Maker Page

### ISSUE THREAD

**Issue by christine-morgado** [DegreeMap/DegreeMap#14]
Important links:
- Figma: https://www.figma.com/files/team/1393781385452898273/project/254672971?fuid=1306729651072959147

## Description

Outline for the Maker page and its various features. The Maker page will contain the bulk of the project, it's where you will be able to make DegreeMaps and do other sophisticated features. Making sure every little feature is communicated with everyone and justified is important.

This epic is made up of various stories that make up a specific part of the Maker page.

## STORY: DegreeMap Section
As a **role**, I want **goal**, so that **reason**.

### Definition of Done
- [ ] Acceptance criteria defined

### Acceptance Criteria
- [ ] Given **initial context**, when **event occurs**, then **some desired outcome**

### Solution Tasks
- [ ] [Task 1]

## STORY: Course Selection Section
As a **role**, I want **goal**, so that **reason**.

### Definition of Done
- [ ] Acceptance criteria defined

### Acceptance Criteria
- [ ] Given **initial context**, when **event occurs**, then **some desired outcome**

### Solution Tasks
- [ ] [Task 1]

## STORY: Toolbar Section
As a **role**, I want **goal**, so that **reason**.

### Definition of Done
- [ ] Acceptance criteria defined

### Acceptance Criteria
- [ ] Given **initial context**, when **event occurs**, then **some desired outcome**

### Solution Tasks
- [ ] [Task 1]
