### ISSUE TITLE
EPIC: Home Page

### ISSUE THREAD

**Issue by christine-morgado** [DegreeMap/DegreeMap#15]
Important links:
- Figma: https://www.figma.com/files/team/1393781385452898273/project/254672971?fuid=1306729651072959147

## Description

Outline for the Home Page. 

## STORY: Signup Button
As a **role**, I want **goal**, so that **reason**.

### Definition of Done
- [ ] Acceptance criteria defined

### Acceptance Criteria
- [ ] Given **initial context**, when **event occurs**, then **some desired outcome**

### Solution Tasks
- [ ] [Task 1]

## STORY: Get Started Button
As a **role**, I want **goal**, so that **reason**.

### Definition of Done
- [ ] Acceptance criteria defined

### Acceptance Criteria
- [ ] Given **initial context**, when **event occurs**, then **some desired outcome**

### Solution Tasks
- [ ] [Task 1]
