### ISSUE TITLE
TASK: User Authentication

### ISSUE THREAD

**Issue by christine-morgado** [DegreeMap/DegreeMap#4]
## Description

Users need to be authenticated properly.

### Subtasks

- [x] Added next-auth (w/ only credential provider)
- [x] JWT handling w/ access tokens
- [x] Dummy protected route (will be removed later)

### *In-Review* Tasks

- [x] Make sure other backend devs are filled in on the changes to user authentication.
- [x] Make sure all devs know how to log in once things are completed.
