### ISSUE TITLE
TASK: Complete Documentation

### ISSUE THREAD

**Issue by christine-morgado** [DegreeMap/DegreeMap#5]
## Description

Some things are hard to decipher at first look. We should do this so the app is easier to dive in when we're messing with code we haven't touched in awhile or ever before. 

### Subtasks

- [ ] Finish next readme.
- [ ] Finish server readme.
- [ ] Finish repository readme (and spruce it up to make the repository look good).

Create adequate documentation for all tests, non-JPA entity files and related files (controllers, repositoryies, etc...). Context for those can be found in the DB schemas file. Can be very simple if needed. 
- [ ] All config files.
- [ ] All auth files.

### *In-Review* Tasks
Have ALL devs review each readme:
- [ ] Next
- [ ] Server
- [ ] Repo
