### ISSUE TITLE
TASK: Initial Front-end Designs

### ISSUE THREAD

**Issue by christine-morgado** [DegreeMap/DegreeMap#9]
## Description

Front-end designs.

### Tasks

- [x] Everyone creates a mockup and reviews it.

Resources: https://www.figma.com/

### Acceptance Criteria

Mockups should have:
- [x] A homepage
- [x] A DegreeMap page
- [x] A profile page

Additionally:
- [x] Create color scheme
- [x] Create layouts for your pages

### *In-Review* Tasks (DUE 7/17 @ 9:30am EST)
- [x] Vote for the best attributes of each one and create a better mockup.
